server:
  port: 8091
spring:
  application:
    name: oauth2-resource-server-jwt

---
spring:
  profiles: local

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
#          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
          public-key-location: classpath:my-key.pub
---
spring:
  profiles: docker

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:
server:
  port: 8090