spring:
  application:
    name: oauth2-auth-server-jwt
server:
  port: 8090

management:
  endpoint:
    health:
      enabled: true
---
spring:
  profiles: local


security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:my-release-key.keystore
        key-alias: alias_name
        key-store-password: jj950303


---
spring:
  profiles: docker

server:
  port: 8090