server:
  port: 8091
spring:
  application:
    name: oauth2-resource-server

---
spring:
  profiles: local

oauth2:
  client-id: user-client
  client-secret: user-secret-8888
  check-token-access: http://localhost:8090/oauth/check_token


---
spring:
  profiles: docker

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      access-token-uri: http://oauth2-auth-server:8090/oauth/token
    resource:
      user-info-uri: fakeurl
    authorization:
      check-token-access: http://oauth2-auth-server:8090/oauth/check_token
server:
  port: 8090